name: copy-main-to-mirror-repo

on:
  push:
    branches:
      - main
      - master

jobs:
  copy-main-to-mirror-repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 'prepare files to copy'
        run: |
          mkdir to-copy
          rsync -a -v --exclude .git . to-copy/
      - name: Copy all files to the mirror repo
        uses: cpina/github-action-push-to-another-repository@v1.7.2
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: 'to-copy'
          destination-github-username: 'nitram509'
          destination-repository-name: 'code-generation-playground-fork'
#          destination-repository-username: 'nitram509'
#          target-branch: 'main'
#          user-name: 'nitram509'
#          user-email: 'maki@bitkings.de'
